### ISSUE TITLE
Hatalı kod

### ISSUE THREAD

**Issue by metinsaritas** [bgoktugozdemir/CSharp#3]
https://github.com/bgoktugozdemir/CSharp/blob/fc4c8e51028ab943f587209b005feffac509b604/Data%20Structures%20-%20Veri%20Yap%C4%B1lar%C4%B1/Heap%20Sort.cs#L128

HeapifyUp(eb); // bu şekilde olmalı

**Comment by bgoktugozdemir** [comment]
👍
